export const Types = {
  // REPOSITORIES
  POST_REPOSITORY: Symbol.for("POST_REPOSITORY"),

  // USECACES
  CREATE_POST_USECASE: Symbol.for("CREATE_POST_USECASE"),
  GET_POST_BY_ID_USECASE: Symbol.for("GET_POST_BY_ID_USECASE"),
  GET_POSTS_USECASE: Symbol.for("GET_POSTS_USECASE"),
  GET_ONE_POST_USECASE: Symbol.for("GET_ONE_POST_USECASE"),
  GET_MANY_POST_USECASE: Symbol.for("GET_MANY_POST_USECASE"),
  UPDATE_POST_USECASE: Symbol.for("UPDATE_POST_USECASE"),
  DELETE_POST_USECASE: Symbol.for("DELETE_POST_USECASE"),

  // services
  POST_SERVICE: Symbol.for("POST_SERVICE"),

  // CONTROLLER
  POST_CONTROLLER: Symbol.for("POST_CONTROLLER"),
};
